name: Docker Image Build and Push

on:
  push:
    tags:
      - '*'  # 触发所有标签的推送

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: hanxuning
  IMAGE_NAME: ai_test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 获取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录容器镜像仓库
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # 获取 Git 标签（将标签赋值给环境变量）
      - name: Get Git tag
        id: get-tag
        run: |
          # 提取 Git 标签并赋值给环境变量
          TAG_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      # 构建并推送镜像（使用 Git 标签作为版本标签）
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          file: ./docker/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}  # 使用 Git 标签作为镜像标签
          labels: version=${{ env.TAG_NAME }}

