name: Docker Image Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: hanxuning
  IMAGE_NAME: ai_test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Get latest git tag
        id: get-latest-tag
        run: |
          # 获取最新的 git 标签，如果没有标签，默认为 v1.0.0
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="v1.0.0"
          fi
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV
          echo "New version tag: $latest_tag"

      - name: Debug version tag
        run: |
          echo "Using version tag: ${{ env.latest_tag }}"

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.latest_tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          file: ./docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clean up old duplicate tags
        run: |
          # 查找仓库中所有现有的标签，删除与当前版本相同的标签
          current_tag="${{ env.latest_tag }}"
          # 列出当前仓库中所有的标签
          existing_tags=$(docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}")
          
          for tag in $existing_tags; do
            # 跳过当前标签
            if [[ "$tag" != *"$current_tag"* ]]; then
              # 删除与当前标签相同的镜像标签
              echo "Removing duplicate tag: $tag"
              docker rmi $tag || true  # 删除该标签
            fi
          done
